#!/usr/bin/env bash
# launch-team.sh — spawn a tmux team of parallel Claude Code workers.
# Generated by the orchestrate-tmux-team plugin (orchestrating-parallel-agents skill).
#
# Subcommands:
#   (none)      Set up worktrees + tmux session.
#   --status    Print STATUS.md from each worker worktree.
#   --cleanup   Tear down session and remove worker worktrees.
#
# STATUS.md state vocabulary (line 1):
#   PENDING                       worker not yet started
#   IN_PROGRESS <task summary>    worker working
#   READY <summary>               worker complete; ready to merge
#   FAILED <reason>               worker hit an error; needs human
#   BLOCKED <reason>              worker waiting on external input

set -euo pipefail

# ─── Parameterized by the skill at render time ────────────────────────────────
SESSION="{{SESSION}}"
WORKTREE_PREFIX="{{WORKTREE_PREFIX}}"
BRANCH_PREFIX="{{BRANCH_PREFIX}}"
COORD_COLOR={{COORD_COLOR}}

# name | branch suffix | tmux 256-color
WORKERS=(
  {{WORKERS}}
)

# Optional pre-staged files (L8 defense): "src-abs|worker1,worker2|dest-rel"
# Empty array if no pre-staging is needed.
STAGED_FILES=(
  {{STAGED_FILES}}
)
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
WORKTREE_ROOT="$REPO_ROOT/.claude/worktrees"
PROMPT_DIR="$REPO_ROOT/.claude/team-prompts"

# ─── Defense L1+L4: rogue-pane cleanup with stability poll ────────────────────
kill_rogue_panes() {
  while IFS=':' read -r idx cwd; do
    if [[ "$cwd" != "$REPO_ROOT"* ]]; then
      tmux kill-pane -t "${SESSION}:team.$idx" 2>/dev/null || true
    fi
  done < <(tmux list-panes -t "${SESSION}:team" -F "#{pane_index}:#{pane_current_path}" | sort -rn)
}

# Wait until pane count is stable for 3 consecutive 100ms checks (catches
# late-injecting tmux plugins like OpenSessions). Total wait <= ~1.5s.
wait_for_panes_stable() {
  local prev=-1 stable=0 i=0
  while (( stable < 3 && i < 15 )); do
    local n
    n=$(tmux list-panes -t "${SESSION}:team" 2>/dev/null | wc -l | tr -d ' ')
    if (( n == prev )); then
      stable=$((stable + 1))
    else
      stable=1
      prev=$n
    fi
    sleep 0.1
    i=$((i + 1))
  done
}

# ─── --status ─────────────────────────────────────────────────────────────────
cmd_status() {
  printf '\n  Worker status (under %s)\n  ─────────────────────\n' "$WORKTREE_ROOT"
  for spec in "${WORKERS[@]}"; do
    IFS='|' read -r name _ _ <<< "$spec"
    s="$WORKTREE_ROOT/${WORKTREE_PREFIX}-$name/STATUS.md"
    if [[ ! -d "$WORKTREE_ROOT/${WORKTREE_PREFIX}-$name" ]]; then
      printf '   ?  %-12s  no worktree\n' "$name"
      continue
    fi
    if [[ ! -f "$s" ]]; then
      printf '   ?  %-12s  PENDING\n' "$name"
      continue
    fi
    line1=$(head -1 "$s")
    case "$line1" in
      READY*)        printf '   \xe2\x9c\x93  %-12s  %s\n' "$name" "$line1" ;;     # ✓
      IN_PROGRESS*)  printf '   \xe2\x80\xa6  %-12s  %s\n' "$name" "$line1" ;;     # …
      FAILED*)       printf '   \xe2\x9c\x97  %-12s  %s\n' "$name" "$line1" ;;     # ✗
      BLOCKED*)      printf '   \xe2\x9b\x94  %-12s  %s\n' "$name" "$line1" ;;     # ⛔
      PENDING*|"")   printf '   ?  %-12s  PENDING\n' "$name" ;;
      *)             printf '   !  %-12s  UNKNOWN: %s\n' "$name" "$line1" ;;
    esac
    if (( $(wc -l < "$s") > 1 )); then
      printf '       (%d more lines in %s)\n' "$(( $(wc -l < "$s") - 1 ))" "$s"
    fi
  done
  printf '\n'
}

# ─── --cleanup ────────────────────────────────────────────────────────────────
cmd_cleanup() {
  tmux kill-session -t "$SESSION" 2>/dev/null || true

  # Detect dirty worktrees and confirm before destruction
  local dirty=()
  for spec in "${WORKERS[@]}"; do
    IFS='|' read -r name _ _ <<< "$spec"
    wt="$WORKTREE_ROOT/${WORKTREE_PREFIX}-$name"
    if [[ -d "$wt" ]]; then
      if [[ -n "$(git -C "$wt" status --porcelain 2>/dev/null)" ]]; then
        dirty+=("$wt")
      fi
    fi
  done
  if (( ${#dirty[@]} > 0 )); then
    echo "⚠  The following worker worktrees have uncommitted changes:"
    printf '   %s\n' "${dirty[@]}"
    read -r -p "Destroy them anyway? [y/N] " ans
    case "$ans" in
      y|Y|yes|YES) ;;
      *) echo "Aborted. Commit or stash worktree changes first."; exit 1 ;;
    esac
  fi

  for spec in "${WORKERS[@]}"; do
    IFS='|' read -r name branch _ <<< "$spec"
    wt="$WORKTREE_ROOT/${WORKTREE_PREFIX}-$name"
    br="${BRANCH_PREFIX}$branch"
    if [[ -d "$wt" ]]; then
      git -C "$REPO_ROOT" worktree remove --force "$wt" 2>/dev/null || rm -rf "$wt"
    fi
    git -C "$REPO_ROOT" branch -D "$br" 2>/dev/null || true
  done
  echo "✓ Session and worktrees cleaned up."
}

# ─── Preflight ────────────────────────────────────────────────────────────────
preflight() {
  command -v tmux >/dev/null 2>&1 || { echo "✗ tmux not installed (required)." >&2; exit 1; }
  command -v git  >/dev/null 2>&1 || { echo "✗ git not installed (required)."  >&2; exit 1; }

  # git ≥ 2.30 for stable worktree behavior
  local gv
  gv=$(git --version | awk '{print $3}')
  IFS='.' read -r maj min _ <<< "$gv"
  if (( maj < 2 || (maj == 2 && min < 30) )); then
    echo "✗ git ≥ 2.30 required for worktree support; have $gv." >&2
    exit 1
  fi

  # Workers' shells: alias-bypass (L2) only works for bash/zsh. fish/csh users
  # must launch panes manually.
  case "${SHELL##*/}" in
    bash|zsh) ;;
    *) echo "⚠  Unsupported shell '$SHELL'; pre-typed 'claude' may not work. Continuing anyway." >&2 ;;
  esac
}

# ─── --launch (default) ───────────────────────────────────────────────────────
created_worktrees=()
created_branches=()

on_launch_fail() {
  echo "" >&2
  echo "✗ Launch failed; rolling back partial state…" >&2
  for wt in "${created_worktrees[@]}"; do
    git -C "$REPO_ROOT" worktree remove --force "$wt" 2>/dev/null || rm -rf "$wt"
  done
  for br in "${created_branches[@]}"; do
    git -C "$REPO_ROOT" branch -D "$br" 2>/dev/null || true
  done
  tmux kill-session -t "$SESSION" 2>/dev/null || true
  echo "✗ Rollback complete. Investigate the error above and retry." >&2
}

cmd_launch() {
  cd "$REPO_ROOT"
  preflight

  trap on_launch_fail ERR

  # Sanity-check rendered prompts
  for spec in "${WORKERS[@]}"; do
    IFS='|' read -r name _ _ <<< "$spec"
    if [[ ! -f "$PROMPT_DIR/$name.md" ]]; then
      echo "✗ Missing prompt: $PROMPT_DIR/$name.md" >&2
      exit 1
    fi
  done
  if [[ ! -f "$PROMPT_DIR/coordinator.md" ]]; then
    echo "✗ Missing prompt: $PROMPT_DIR/coordinator.md" >&2
    exit 1
  fi

  # Branch-exists guard (P0 patch — actionable error)
  for spec in "${WORKERS[@]}"; do
    IFS='|' read -r _ branch _ <<< "$spec"
    br="${BRANCH_PREFIX}$branch"
    if git show-ref --quiet "refs/heads/$br"; then
      echo "✗ Branch '$br' already exists." >&2
      echo "  Run: bash $0 --cleanup" >&2
      echo "  Then re-launch." >&2
      exit 1
    fi
  done

  mkdir -p "$WORKTREE_ROOT"

  # Create worktrees from current HEAD; track for rollback on failure.
  for spec in "${WORKERS[@]}"; do
    IFS='|' read -r name branch _ <<< "$spec"
    wt="$WORKTREE_ROOT/${WORKTREE_PREFIX}-$name"
    br="${BRANCH_PREFIX}$branch"
    if [[ ! -d "$wt" ]]; then
      git worktree add -b "$br" "$wt" HEAD >/dev/null
      created_worktrees+=("$wt")
      created_branches+=("$br")
      echo "  + worktree: $wt  (branch: $br)"
    else
      echo "  = worktree exists: $wt"
    fi
    cp "$PROMPT_DIR/$name.md" "$wt/TASK.md"
    # Seed STATUS.md so cmd_status shows PENDING immediately.
    [[ -f "$wt/STATUS.md" ]] || echo "PENDING" > "$wt/STATUS.md"
  done

  # L8 — pre-stage cross-worker compile dependencies, if any.
  for spec in "${STAGED_FILES[@]}"; do
    [[ -z "$spec" ]] && continue
    IFS='|' read -r src targets dest <<< "$spec"
    IFS=',' read -ra worker_list <<< "$targets"
    for w in "${worker_list[@]}"; do
      target="$WORKTREE_ROOT/${WORKTREE_PREFIX}-$w/$dest"
      mkdir -p "$(dirname "$target")"
      cp "$src" "$target"
      echo "  ≡ pre-staged $dest → $w"
    done
  done

  # Fresh tmux session
  tmux kill-session -t "$SESSION" 2>/dev/null || true
  tmux new-session -d -s "$SESSION" -n "team" -c "$REPO_ROOT"

  # L1 first pass + L4 stability poll
  wait_for_panes_stable
  kill_rogue_panes

  # L2 — bypass cat=bat alias on every pane shell command
  UNALIAS='unalias cat 2>/dev/null; '

  # Coordinator pane (pane 0 — main repo cwd)
  tmux send-keys -t "${SESSION}:team.0" \
    "${UNALIAS}clear; printf '\\033[1;38;5;${COORD_COLOR}m═══════════════════════════════════════\\n  🎯 COORDINATOR  (branch: $(git rev-parse --abbrev-ref HEAD))\\n  Watches workers; merges when STATUS.md = READY\\n═══════════════════════════════════════\\033[0m\\n\\n'; command cat .claude/team-prompts/coordinator.md; printf '\\n\\n── Tip: bash scripts/launch-team.sh --status to poll ──\\n'" C-m

  # Worker panes
  for i in "${!WORKERS[@]}"; do
    IFS='|' read -r name branch color <<< "${WORKERS[$i]}"
    wt="$WORKTREE_ROOT/${WORKTREE_PREFIX}-$name"
    tmux split-window -t "${SESSION}:team" -c "$wt"
    tmux select-layout -t "${SESSION}:team" tiled
    # L5 — split into two send-keys: first executes the display command,
    # second pre-types 'claude' onto the next prompt without C-m.
    tmux send-keys -t "${SESSION}:team" \
      "${UNALIAS}clear; printf '\\033[1;38;5;${color}m▼ WORKER: ${name}\\nBranch:   ${BRANCH_PREFIX}${branch}\\nWorktree: $(pwd)\\n▲\\033[0m\\n\\n── TASK ──\\n'; command cat TASK.md; printf '\\n\\n▶ Hit Enter to launch claude, then paste the task above as your first message.\\n'" C-m
    tmux send-keys -t "${SESSION}:team" "claude"
  done

  # L1 second pass — catches plugins that inject after split-window
  wait_for_panes_stable
  kill_rogue_panes

  # L4 — colour each pane by its cwd (stable across kill-pane reindexing)
  tmux select-layout -t "${SESSION}:team" tiled
  while IFS=':' read -r idx cwd; do
    color=""
    if [[ "$cwd" == "$REPO_ROOT" ]]; then
      color=$COORD_COLOR
    else
      for spec in "${WORKERS[@]}"; do
        IFS='|' read -r wname _ wcolor <<< "$spec"
        if [[ "$cwd" == "$WORKTREE_ROOT/${WORKTREE_PREFIX}-$wname" ]]; then
          color=$wcolor
          break
        fi
      done
    fi
    if [[ -n "$color" ]]; then
      tmux select-pane -t "${SESSION}:team.$idx" -P "fg=colour${color}"
    fi
  done < <(tmux list-panes -t "${SESSION}:team" -F "#{pane_index}:#{pane_current_path}")

  # Status bar
  tmux set-option -t "$SESSION" status-style "bg=colour234,fg=colour226,bold"
  tmux set-option -t "$SESSION" status-left  "  🎨 ${SESSION} │ "
  tmux set-option -t "$SESSION" status-right "│ %H:%M  "
  tmux set-option -t "$SESSION" pane-border-status top
  tmux set-option -t "$SESSION" pane-border-format " #{pane_index}: #{pane_current_command} "

  trap - ERR

  printf '\n✓ Team session ready: %s\n\n' "$SESSION"
  printf '  ▶ Watch the team:   tmux attach -t %s\n' "$SESSION"
  printf '  ▶ Detach:           Ctrl-b  then  d\n'
  printf '  ▶ Cycle panes:      Ctrl-b  then  o\n'
  printf '  ▶ Poll status:      bash scripts/launch-team.sh --status\n'
  printf '  ▶ Tear down:        bash scripts/launch-team.sh --cleanup\n\n'
  printf 'In each worker pane: hit Enter to launch claude, then paste the task brief\n'
  printf 'shown above the prompt as your first message. The coordinator pane stays idle\n'
  printf 'until all workers report READY.\n\n'
}

case "${1:-}" in
  --status)  cmd_status ;;
  --cleanup) cmd_cleanup ;;
  "")        cmd_launch ;;
  *)         echo "Usage: $0 [--status|--cleanup]" >&2; exit 1 ;;
esac
